### PR TITLE
Try to use newer libsodium

### PR DESCRIPTION
**Pull request by Ekstazi**
attempt to fix travis build

### CODE REVIEW

**Comment by joelwurtz** [comment]
Thanks maybe it would be better to directly compile it from source: see this file for an example: https://github.com/jedisct1/libsodium-php/blob/master/.travis.yml

AFAIK libsodium from this ppa is the 1.0.3 version (see https://launchpad.net/~chris-lea/+archive/ubuntu/libsodium) so it will not fix the issue

**Comment by Ekstazi** [comment]
I switched php versions to 7.2, 7.3, 7.4 and 8 because trusty doesn't support newer libsodium version. May be you can change vm image to xenial or disco ?

**Comment by Ekstazi** [comment]
> Thanks maybe it would be better to directly compile it from source: see this file for an example: https://github.com/jedisct1/libsodium-php/blob/master/.travis.yml
> 
> AFAIK libsodium from this ppa is the 1.0.3 version (see https://launchpad.net/~chris-lea/+archive/ubuntu/libsodium) so it will not fix the issue
I'll try to test it tomorrow

**Comment by Ekstazi** [comment]
I returned back php 7.0 and 7.1. libsodium now builded from source. So i finished. Your can merge this pull request to master

**Comment by joelwurtz** [comment]
Thanks

**Pull request merged**
